version: '3.4'
services:
  loader:
    image: "sbender9/victron-loader"
    volumes:
     - "./config:/config"
    env_file:
     - loader.env
    network_mode: host
  influxdb:
    image: "influxdb:1.7"
    ports:
     - "8086:8086"
    volumes:
     - "influxdb-storage:/var/lib/influxdb"
    environment:
     - INFLUXDB_HTTP_LOG_ENABLED=false
  grafana:
    image: "sbender9/victron-grafana"
    volumes:
     - "grafana-storage:/var/lib/grafana"
    ports:
     - "3000:3000"
    
volumes:
 influxdb-storage:
 grafana-storage:

