version: '3'
services:
  loader:
    image: "sbender9/victron-loader"
    environment:
     - VRM_USER_NAME=username
     - VRM_PASSWORD=password
    links:
      - influxdb
    logging:
      driver: awslogs
      options: 
        awslogs-group: victron-venus
        awslogs-region: us-east-1
        awslogs-stream-prefix: loader
  influxdb:
    image: "influxdb:1.7"
    ports:
     - "8086:8086"
    volumes:
     - "influxdb-storage:/var/lib/influxdb"
    environment:
     - INFLUXDB_HTTP_LOG_ENABLED=false
    logging:
      driver: awslogs
      options: 
        awslogs-group: victron-venus
        awslogs-region: us-east-1
        awslogs-stream-prefix: influxdb
  grafana:
    image: "sbender9/victron-grafana"
    links:
      - influxdb
    volumes:
     - "grafana-storage:/var/lib/grafana"
    ports:
     - "3000:3000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: victron-venus
        awslogs-region: us-east-1
        awslogs-stream-prefix: grafana
    
volumes:
 influxdb-storage:
 grafana-storage:

